### ISSUE TITLE
Unable to send messages bot framework

### ISSUE THREAD

**Issue by ManojAbburi** [qxsch/ChatBot#2]
I am unable to test bot from bot framework portal. I have hosted bot in local IIS server. It is working perfectly in emulator(I have provided App ID and password as well). But i am unable to pass the test in bot framework portal. I tried creating Facebook messenger channel which doesn't work either.

I have attached the screen shots of the problem. Any help will be highly appreciated. Thanks in advance

![boterror](https://user-images.githubusercontent.com/30693598/31543396-764eecea-b033-11e7-826a-f0052b70f778.PNG)

**Comment by qxsch** [comment]
Please Post your Custom ChatSessionInterface, that adds support the bot framework

**Comment by ManojAbburi** [comment]
I don't have anything like Custom Chat, but i tried connecting to Facebook messenger which doesn't work either. It is working fine with bot framework channel emulator.

**Comment by daFiter** [comment]
@ManojAbburi I am trying to get my bot to work on iis what settings did you enable on your server? What does your web.config file look like?

**Comment by ManojAbburi** [comment]
@daFiter Just host the bot using IIS like just you do for normal websites. No need to make any changes in web.config file.In case if you have provided Microsoft App Id and secret key in web.config, do provide these while running the bot on emulator.

**Comment by ManojAbburi** [comment]
I got the solution for this issue,problem is with my messaging end point. Instead of yourbot.com/**api/message**s i provided only yourbot.com in the end point url while configuring bot in bot framework. Just make this small change and it will work.

**Comment by daFiter** [comment]
@ManojAbburi  Is that because in your app.js you don't have this:
server.post('/api/messages', connector.listen());

**Comment by ManojAbburi** [comment]
@daFiter Actually i am using C# to develop the bot. And it occured because i did not give message endpoint url correctly. As shown below.
![bot](https://user-images.githubusercontent.com/30693598/32644841-27041b1e-c60a-11e7-83b9-c9081787033b.PNG)
